### ISSUE TITLE
Add Feature to Archive Favorite Posts

### ISSUE THREAD

**Issue by JahnaviMandadi25** [JahnaviMandadi25/microblog#4]
Users should have the ability to archive posts by adding them to a "favorite list." If the original poster deletes the post, it will remain available only to users who have archived it in their favorites. Favorite lists should be private and only visible to their respective owners.

Expected Behavior:
Users can mark posts as favorites and add them to a private list.
If the original post is deleted, the post will remain available to users who have it in their favorite list.
Favorite lists will be private and accessible only by their owners.

Estimate: 2 weeks

**Comment by PrajwalBanakar** [comment]
Added favorite feature where user can add , remove and view favorite posts.
